from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class LogEntry(BaseModel):
    """Represents an individual log entry."""
    timestamp: datetime
    level: str
    message: str
    service_name: Optional[str] = None
    trace_id: Optional[str] = None
    span_id: Optional[str] = None
    attributes: Dict[str, Any] = Field(default_factory=dict)

class TelemetryContext(BaseModel):
    """Telemetry context collected for analysis."""
    service_name: str
    logs: List[LogEntry] = Field(default_factory=list)
    metrics: List[Dict[str, Any]] = Field(default_factory=list)
    spans: List[Dict[str, Any]] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

class DiagnosticResult(BaseModel):
    """Analysis result generated by the LLM."""
    summary: str = Field(description="Executive summary of the issue")
    root_cause: str = Field(description="Identified root cause")
    impact_analysis: str = Field(description="System impact analysis")
    suggested_actions: List[str] = Field(description="Recommended steps for mitigation and resolution")
    confidence_score: float = Field(ge=0, le=1, description="Diagnostic confidence level (0-1)")

class DiagnosticReport(BaseModel):
    """Final diagnostic report."""
    report_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    context: TelemetryContext
    diagnosis: DiagnosticResult
